export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BESTS_FETCHED = "BESTS_FETCHED";
export const POPULARS_FETCHED = "POPULARS_FETCHED";
export const SUGGESTS_FETCHED = "SUGGESTS_FETCHED";
export const LANDING_FETCHED = "LANDING_FETCHED";
export const USER_POST_REVIEW = "USER_POST_REVIEW";